package cn.skcks.docking.gb28181.orm.mybatis.basic.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table docking_device
 */
public class DockingDevice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.manufacturer
     *
     * @mbg.generated
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.firmware
     *
     * @mbg.generated
     */
    private String firmware;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.transport
     *
     * @mbg.generated
     */
    private String transport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.stream_mode
     *
     * @mbg.generated
     */
    private String streamMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.on_line
     *
     * @mbg.generated
     */
    private Boolean onLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.register_time
     *
     * @mbg.generated
     */
    private String registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.keepalive_time
     *
     * @mbg.generated
     */
    private String keepaliveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.expires
     *
     * @mbg.generated
     */
    private Integer expires;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.subscribe_cycle_for_catalog
     *
     * @mbg.generated
     */
    private Integer subscribeCycleForCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.subscribe_cycle_for_mobile_position
     *
     * @mbg.generated
     */
    private Integer subscribeCycleForMobilePosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.mobile_position_submission_interval
     *
     * @mbg.generated
     */
    private Integer mobilePositionSubmissionInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.subscribe_cycle_for_alarm
     *
     * @mbg.generated
     */
    private Integer subscribeCycleForAlarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.host_address
     *
     * @mbg.generated
     */
    private String hostAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.charset
     *
     * @mbg.generated
     */
    private String charset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.ssrc_check
     *
     * @mbg.generated
     */
    private Boolean ssrcCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.geo_coord_sys
     *
     * @mbg.generated
     */
    private String geoCoordSys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.media_server_id
     *
     * @mbg.generated
     */
    private String mediaServerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.custom_name
     *
     * @mbg.generated
     */
    private String customName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.sdp_ip
     *
     * @mbg.generated
     */
    private String sdpIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.local_ip
     *
     * @mbg.generated
     */
    private String localIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.as_message_channel
     *
     * @mbg.generated
     */
    private Boolean asMessageChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.keepalive_interval_time
     *
     * @mbg.generated
     */
    private Integer keepaliveIntervalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.switch_primary_sub_stream
     *
     * @mbg.generated
     */
    private Boolean switchPrimarySubStream;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column docking_device.broadcast_push_after_ack
     *
     * @mbg.generated
     */
    private Boolean broadcastPushAfterAck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.id
     *
     * @return the value of docking_device.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.id
     *
     * @param id the value for docking_device.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.device_id
     *
     * @return the value of docking_device.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.device_id
     *
     * @param deviceId the value for docking_device.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.name
     *
     * @return the value of docking_device.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.name
     *
     * @param name the value for docking_device.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.manufacturer
     *
     * @return the value of docking_device.manufacturer
     *
     * @mbg.generated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.manufacturer
     *
     * @param manufacturer the value for docking_device.manufacturer
     *
     * @mbg.generated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.model
     *
     * @return the value of docking_device.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.model
     *
     * @param model the value for docking_device.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.firmware
     *
     * @return the value of docking_device.firmware
     *
     * @mbg.generated
     */
    public String getFirmware() {
        return firmware;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.firmware
     *
     * @param firmware the value for docking_device.firmware
     *
     * @mbg.generated
     */
    public void setFirmware(String firmware) {
        this.firmware = firmware == null ? null : firmware.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.transport
     *
     * @return the value of docking_device.transport
     *
     * @mbg.generated
     */
    public String getTransport() {
        return transport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.transport
     *
     * @param transport the value for docking_device.transport
     *
     * @mbg.generated
     */
    public void setTransport(String transport) {
        this.transport = transport == null ? null : transport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.stream_mode
     *
     * @return the value of docking_device.stream_mode
     *
     * @mbg.generated
     */
    public String getStreamMode() {
        return streamMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.stream_mode
     *
     * @param streamMode the value for docking_device.stream_mode
     *
     * @mbg.generated
     */
    public void setStreamMode(String streamMode) {
        this.streamMode = streamMode == null ? null : streamMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.on_line
     *
     * @return the value of docking_device.on_line
     *
     * @mbg.generated
     */
    public Boolean getOnLine() {
        return onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.on_line
     *
     * @param onLine the value for docking_device.on_line
     *
     * @mbg.generated
     */
    public void setOnLine(Boolean onLine) {
        this.onLine = onLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.register_time
     *
     * @return the value of docking_device.register_time
     *
     * @mbg.generated
     */
    public String getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.register_time
     *
     * @param registerTime the value for docking_device.register_time
     *
     * @mbg.generated
     */
    public void setRegisterTime(String registerTime) {
        this.registerTime = registerTime == null ? null : registerTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.keepalive_time
     *
     * @return the value of docking_device.keepalive_time
     *
     * @mbg.generated
     */
    public String getKeepaliveTime() {
        return keepaliveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.keepalive_time
     *
     * @param keepaliveTime the value for docking_device.keepalive_time
     *
     * @mbg.generated
     */
    public void setKeepaliveTime(String keepaliveTime) {
        this.keepaliveTime = keepaliveTime == null ? null : keepaliveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.ip
     *
     * @return the value of docking_device.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.ip
     *
     * @param ip the value for docking_device.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.create_time
     *
     * @return the value of docking_device.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.create_time
     *
     * @param createTime the value for docking_device.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.update_time
     *
     * @return the value of docking_device.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.update_time
     *
     * @param updateTime the value for docking_device.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.port
     *
     * @return the value of docking_device.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.port
     *
     * @param port the value for docking_device.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.expires
     *
     * @return the value of docking_device.expires
     *
     * @mbg.generated
     */
    public Integer getExpires() {
        return expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.expires
     *
     * @param expires the value for docking_device.expires
     *
     * @mbg.generated
     */
    public void setExpires(Integer expires) {
        this.expires = expires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.subscribe_cycle_for_catalog
     *
     * @return the value of docking_device.subscribe_cycle_for_catalog
     *
     * @mbg.generated
     */
    public Integer getSubscribeCycleForCatalog() {
        return subscribeCycleForCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.subscribe_cycle_for_catalog
     *
     * @param subscribeCycleForCatalog the value for docking_device.subscribe_cycle_for_catalog
     *
     * @mbg.generated
     */
    public void setSubscribeCycleForCatalog(Integer subscribeCycleForCatalog) {
        this.subscribeCycleForCatalog = subscribeCycleForCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.subscribe_cycle_for_mobile_position
     *
     * @return the value of docking_device.subscribe_cycle_for_mobile_position
     *
     * @mbg.generated
     */
    public Integer getSubscribeCycleForMobilePosition() {
        return subscribeCycleForMobilePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.subscribe_cycle_for_mobile_position
     *
     * @param subscribeCycleForMobilePosition the value for docking_device.subscribe_cycle_for_mobile_position
     *
     * @mbg.generated
     */
    public void setSubscribeCycleForMobilePosition(Integer subscribeCycleForMobilePosition) {
        this.subscribeCycleForMobilePosition = subscribeCycleForMobilePosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.mobile_position_submission_interval
     *
     * @return the value of docking_device.mobile_position_submission_interval
     *
     * @mbg.generated
     */
    public Integer getMobilePositionSubmissionInterval() {
        return mobilePositionSubmissionInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.mobile_position_submission_interval
     *
     * @param mobilePositionSubmissionInterval the value for docking_device.mobile_position_submission_interval
     *
     * @mbg.generated
     */
    public void setMobilePositionSubmissionInterval(Integer mobilePositionSubmissionInterval) {
        this.mobilePositionSubmissionInterval = mobilePositionSubmissionInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.subscribe_cycle_for_alarm
     *
     * @return the value of docking_device.subscribe_cycle_for_alarm
     *
     * @mbg.generated
     */
    public Integer getSubscribeCycleForAlarm() {
        return subscribeCycleForAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.subscribe_cycle_for_alarm
     *
     * @param subscribeCycleForAlarm the value for docking_device.subscribe_cycle_for_alarm
     *
     * @mbg.generated
     */
    public void setSubscribeCycleForAlarm(Integer subscribeCycleForAlarm) {
        this.subscribeCycleForAlarm = subscribeCycleForAlarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.host_address
     *
     * @return the value of docking_device.host_address
     *
     * @mbg.generated
     */
    public String getHostAddress() {
        return hostAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.host_address
     *
     * @param hostAddress the value for docking_device.host_address
     *
     * @mbg.generated
     */
    public void setHostAddress(String hostAddress) {
        this.hostAddress = hostAddress == null ? null : hostAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.charset
     *
     * @return the value of docking_device.charset
     *
     * @mbg.generated
     */
    public String getCharset() {
        return charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.charset
     *
     * @param charset the value for docking_device.charset
     *
     * @mbg.generated
     */
    public void setCharset(String charset) {
        this.charset = charset == null ? null : charset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.ssrc_check
     *
     * @return the value of docking_device.ssrc_check
     *
     * @mbg.generated
     */
    public Boolean getSsrcCheck() {
        return ssrcCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.ssrc_check
     *
     * @param ssrcCheck the value for docking_device.ssrc_check
     *
     * @mbg.generated
     */
    public void setSsrcCheck(Boolean ssrcCheck) {
        this.ssrcCheck = ssrcCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.geo_coord_sys
     *
     * @return the value of docking_device.geo_coord_sys
     *
     * @mbg.generated
     */
    public String getGeoCoordSys() {
        return geoCoordSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.geo_coord_sys
     *
     * @param geoCoordSys the value for docking_device.geo_coord_sys
     *
     * @mbg.generated
     */
    public void setGeoCoordSys(String geoCoordSys) {
        this.geoCoordSys = geoCoordSys == null ? null : geoCoordSys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.media_server_id
     *
     * @return the value of docking_device.media_server_id
     *
     * @mbg.generated
     */
    public String getMediaServerId() {
        return mediaServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.media_server_id
     *
     * @param mediaServerId the value for docking_device.media_server_id
     *
     * @mbg.generated
     */
    public void setMediaServerId(String mediaServerId) {
        this.mediaServerId = mediaServerId == null ? null : mediaServerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.custom_name
     *
     * @return the value of docking_device.custom_name
     *
     * @mbg.generated
     */
    public String getCustomName() {
        return customName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.custom_name
     *
     * @param customName the value for docking_device.custom_name
     *
     * @mbg.generated
     */
    public void setCustomName(String customName) {
        this.customName = customName == null ? null : customName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.sdp_ip
     *
     * @return the value of docking_device.sdp_ip
     *
     * @mbg.generated
     */
    public String getSdpIp() {
        return sdpIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.sdp_ip
     *
     * @param sdpIp the value for docking_device.sdp_ip
     *
     * @mbg.generated
     */
    public void setSdpIp(String sdpIp) {
        this.sdpIp = sdpIp == null ? null : sdpIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.local_ip
     *
     * @return the value of docking_device.local_ip
     *
     * @mbg.generated
     */
    public String getLocalIp() {
        return localIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.local_ip
     *
     * @param localIp the value for docking_device.local_ip
     *
     * @mbg.generated
     */
    public void setLocalIp(String localIp) {
        this.localIp = localIp == null ? null : localIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.password
     *
     * @return the value of docking_device.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.password
     *
     * @param password the value for docking_device.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.as_message_channel
     *
     * @return the value of docking_device.as_message_channel
     *
     * @mbg.generated
     */
    public Boolean getAsMessageChannel() {
        return asMessageChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.as_message_channel
     *
     * @param asMessageChannel the value for docking_device.as_message_channel
     *
     * @mbg.generated
     */
    public void setAsMessageChannel(Boolean asMessageChannel) {
        this.asMessageChannel = asMessageChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.keepalive_interval_time
     *
     * @return the value of docking_device.keepalive_interval_time
     *
     * @mbg.generated
     */
    public Integer getKeepaliveIntervalTime() {
        return keepaliveIntervalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.keepalive_interval_time
     *
     * @param keepaliveIntervalTime the value for docking_device.keepalive_interval_time
     *
     * @mbg.generated
     */
    public void setKeepaliveIntervalTime(Integer keepaliveIntervalTime) {
        this.keepaliveIntervalTime = keepaliveIntervalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.switch_primary_sub_stream
     *
     * @return the value of docking_device.switch_primary_sub_stream
     *
     * @mbg.generated
     */
    public Boolean getSwitchPrimarySubStream() {
        return switchPrimarySubStream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.switch_primary_sub_stream
     *
     * @param switchPrimarySubStream the value for docking_device.switch_primary_sub_stream
     *
     * @mbg.generated
     */
    public void setSwitchPrimarySubStream(Boolean switchPrimarySubStream) {
        this.switchPrimarySubStream = switchPrimarySubStream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column docking_device.broadcast_push_after_ack
     *
     * @return the value of docking_device.broadcast_push_after_ack
     *
     * @mbg.generated
     */
    public Boolean getBroadcastPushAfterAck() {
        return broadcastPushAfterAck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column docking_device.broadcast_push_after_ack
     *
     * @param broadcastPushAfterAck the value for docking_device.broadcast_push_after_ack
     *
     * @mbg.generated
     */
    public void setBroadcastPushAfterAck(Boolean broadcastPushAfterAck) {
        this.broadcastPushAfterAck = broadcastPushAfterAck;
    }
}