package cn.skcks.docking.gb28181.orm.mybatis.dynamic.model;

import jakarta.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table docking_device_channel
 */
public class DockingDeviceChannel {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.id")
    private Long id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.gb_device_id")
    private String gbDeviceId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.gb_device_channel_id")
    private String gbDeviceChannelId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.name")
    private String name;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.address")
    private String address;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.id")
    public Long getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.id")
    public void setId(Long id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.gb_device_id")
    public String getGbDeviceId() {
        return gbDeviceId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.gb_device_id")
    public void setGbDeviceId(String gbDeviceId) {
        this.gbDeviceId = gbDeviceId == null ? null : gbDeviceId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.gb_device_channel_id")
    public String getGbDeviceChannelId() {
        return gbDeviceChannelId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.gb_device_channel_id")
    public void setGbDeviceChannelId(String gbDeviceChannelId) {
        this.gbDeviceChannelId = gbDeviceChannelId == null ? null : gbDeviceChannelId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.name")
    public String getName() {
        return name;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.name")
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.address")
    public String getAddress() {
        return address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: docking_device_channel.address")
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}